version: '3.1'

services:
  db:
    image: mysql:5.7.30
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_USER: deno
      MYSQL_PASSWORD: demo
      MYSQL_DATABASE: terrain
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
  app:
    depends_on:
      - db
    user: deno
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 5000:5000
      - 9229:9229
    environment:
      DB_USER: deno
      DB_PWD: demo
volumes:
  db_data: {}
